name: Jekyll site CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Build the site in the jekyll/builder container
        uses: actions/checkout@v3
      - run: |
          python3 --version
          docker run \
          -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
          jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
      - run: |
          pwd
          echo "Exporting pdf"
          brew install weasyprint
          weasyprint -e "utf-8" -s assets/styles/cv.css https://awlobo.github.io/about/ assets/cv.pdf
      - run: echo "Done!"
